edition: 1.0.0
name: serverless-cd
access: default_serverless_devs_access

vars:
  region: 'ap-southeast-1'
  service:
    name: 'serverless-cd'
    description: Serverless-cd 应用
    logConfig: auto
    nasConfig: auto
  workerFunctionName: worker
  adminFunctionName: admin
  workerDeliverFunctionName: workerDeliver
  domain: 'app.serverless-cd.cn'
  logLocalPathPrefix: /mnt/auto/logs
  databaseUrl: '${env.DATABASE_URL}'
  prisma: 'mongodb'

services:
  worker:
    component: fc
    actions:
      pre-deploy:
        - run: npm install --registry=https://registry.npmmirror.com
          path: '../src/worker'
      post-deploy:
        - component: fc api UpdateFunction --region ${vars.region} --header
            '{"x-fc-disable-container-reuse":"True"}' --path
            '{"serviceName":"${vars.service.name}","functionName":"${vars.workerFunctionName}"}'
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: ${vars.workerFunctionName}
        description: 执行用户配置的 CD 流程。
        runtime: custom
        codeUri: ../src/worker
        customRuntimeConfig:
          command:
            - node
            - server
        memorySize: 2048
        timeout: 3600
        layers:
          - acs:fc:${vars.region}:official:layers/Nodejs16/versions/1
        environmentVariables:
          PATH: /opt:/opt/nodejs16/bin:/usr/local/bin/apache-maven/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ruby/bin
          DOMAIN: ${vars.domain} # 用于给用户显示日志链接地址
          LOG_LOCAL_PATH_PREFIX: ${vars.logLocalPathPrefix}
        asyncConfiguration:
          maxAsyncRetryAttempts: 0
          statefulInvocation: true
          destination:
            onFailure: acs:fc:::services/${vars.service.name}/functions/${vars.workerDeliverFunctionName}

  worker-deliver:
    component: fc
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: ${vars.workerDeliverFunctionName}
        description: 执行用户配置的 CD 流程。
        runtime: nodejs14
        codeUri: ../src/worker
        handler: deliver.handler
        memorySize: 640
        timeout: 600
        asyncConfiguration:
          maxAsyncRetryAttempts: 0

  admin: # Admin 控制台提供Api Server函数
    component: fc
    actions:
      pre-deploy:
        - run: npm install --registry=https://registry.npmmirror.com
          path: '../src/admin/public'
        - run: npm run build
          path: '../src/admin/public'
        - run: npm install --registry=https://registry.npmmirror.com
          path: '../src/admin'
        - run: npx serverless-script setup --file-path ../../deploy --generate
          path: '../src/admin'

    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: ${vars.adminFunctionName}
        description: serverless-cd 前端应用接口
        runtime: custom
        codeUri: ../src/admin
        handler: index.handler
        initializer: index.initializer
        initializationTimeout: 30
        memorySize: 640
        timeout: 360
        caPort: 9000
        instanceConcurrency: 5
        customRuntimeConfig:
          command:
            - node
            - index.js
        layers:
          - acs:fc:${vars.region}:official:layers/Nodejs16/versions/2
          - acs:fc:${vars.region}:official:layers/SQLite3/versions/1
        environmentVariables:
          PATH: /opt:/opt/nodejs16/bin:/usr/local/bin/apache-maven/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ruby/bin
          DATABASE_URL: ${vars.databaseUrl} # 用于链接数据库
          LOG_LOCAL_PATH_PREFIX: ${vars.logLocalPathPrefix}
          JWT_SECRET: ${env.JWT_SECRET}
          WEBHOOK_URL: http://${vars.domain}
      triggers:
        - name: http-trigger
          type: http
          config:
            authType: anonymous
            methods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
      customDomains:
        - domainName: 'app.serverless-cd.cn'
          protocol: HTTP,HTTPS
          certId: 9493156
          tlsConfig:
            minVersion: TLSv1.2
            maxVersion: TLSv1.3
            cipherSuites:
              - TLS_RSA_WITH_AES_128_CBC_SHA
              - TLS_RSA_WITH_AES_256_CBC_SHA
              - TLS_RSA_WITH_AES_128_GCM_SHA256
              - TLS_RSA_WITH_AES_256_GCM_SHA384
              - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
              - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
              - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
              - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
              - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
              - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
              - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
              - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
              - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
              - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
          routeConfigs:
            - path: /*
