cd("{{secrets.DOWNLOAD_CODE_DIR}}");
await $`pwd`;
await $`echo SESSION_EXPIRATION={{secrets.SESSION_EXPIRATION}} >> .env`;
await $`echo DOWNLOAD_CODE_DIR={{secrets.DOWNLOAD_CODE_DIR}} >> .env`;
await $`echo CD_PIPLINE_YAML={{secrets.CD_PIPLINE_YAML}} >> .env`;
await $`echo REGION={{secrets.REGION}} >> .env`;
await $`echo OSS_BUCKET={{secrets.OSS_BUCKET}} >> .env`;
await $`echo OTS_INSTANCE_NAME={{secrets.OTS_INSTANCE_NAME}} >> .env`;
await $`echo DOMAIN={{secrets.DOMAIN}} >> .env`;
await $`echo OTS_TASK_TABLE_NAME={{secrets.OTS_TASK_TABLE_NAME}} >> .env`;
await $`echo OTS_USER_TABLE_NAME={{secrets.OTS_USER_TABLE_NAME}} >> .env`;
await $`echo OTS_APP_TABLE_NAME={{secrets.OTS_APP_TABLE_NAME}} >> .env`;
await $`echo OTS_TOKEN_TABLE_NAME={{secrets.OTS_TOKEN_TABLE_NAME}} >> .env`;
await $`echo OTS_SESSION_TABLE_NAME={{secrets.OTS_SESSION_TABLE_NAME}} >> .env`;
await $`echo OTS_TASK_INDEX_NAME={{secrets.OTS_TASK_INDEX_NAME}} >> .env`;
await $`echo OTS_USER_INDEX_NAME={{secrets.OTS_USER_INDEX_NAME}} >> .env`;
await $`echo OTS_APP_INDEX_NAME={{secrets.OTS_APP_INDEX_NAME}} >> .env`;
await $`echo OTS_TOKEN_INDEX_NAME={{secrets.OTS_TOKEN_INDEX_NAME}} >> .env`;
await $`echo ACCOUNTID={{secrets.ACCOUNTID}} >> .env`;
await $`echo ACCESS_KEY_ID={{secrets.ACCESS_KEY_ID}} >> .env`;
await $`echo ACCESS_KEY_SECRET={{secrets.ACCESS_KEY_SECRET}} >> .env`;
