edition: 1.0.0
name: serverless-cd
access: dankun

vars:
  region: ${env.REGION}
  service:
    name: ${env.SERVICE_NAME}
    description: Serverless-cd 应用
    # role: '' # invoke fc ｜ sls | 投递日志（nas  oss）
    logConfig: auto
    vpcConfig:
      securityGroupId: sg-j6c3tx86c5bmqkrxqje5
      vpcId: vpc-j6c2i8puxjnpgcn9iyozu
      vswitchIds:
        - vsw-j6cxtxs9bj47q3xm7g4dm
    nasConfig:
      userId: 0
      groupId: 0
      mountPoints:
        - serverAddr: 12eb804bf71-mog39.cn-hongkong.nas.aliyuncs.com
          nasDir: /serverless-cd-wss
          fcDir: /mnt/auto
  masterFunctionName: master
  workerFunctionName: worker
  adminFunctionName: admin
  workerDeliverFunctionName: workerDeliver
  domain: ${env.DOMAIN}
  sqliteLayer: acs:fc:cn-hongkong:1740298130743624:layers/sqlite3x16/versions/1 # 落泥
  path: /opt:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/fc/lang/nodejs14_alinode/bin:/opt/bin

services:
  master:
    component: fc
    actions:
      pre-deploy:
        - run: npm install --registry=https://registry.npmmirror.com
          path: "./master"
        - run: npx prisma generate
          path: "./master"
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: ${vars.masterFunctionName}
        description: 用于验证 CD的触发方式、请求的合法性以及组装一些 worker 函数需要的内容
        runtime: nodejs14
        codeUri: ./master
        handler: index.handler
        memorySize: 640
        timeout: 12
        instanceConcurrency: 20
        layers:
          - ${vars.sqliteLayer}
        environmentVariables:
          PATH: ${vars.path}
          # 用于链接数据库
          DATABASE_URL: ${env.DATABASE_URL}
          # 阿里云密钥
          ACCOUNT_ID: ${env.ACCOUNT_ID}
          ACCESS_KEY_ID: ${env.ACCESS_KEY_ID}
          ACCESS_KEY_SECRET: ${env.ACCESS_KEY_SECRET}
          # 部署的区域
          REGION: ${vars.region}
          # 部署函数的服务名称
          SERVICE_NAME: ${vars.service.name}
          # worker 函数的名称
          WORKER_FUNCTION_NAME: ${vars.workerFunctionName}
      triggers:
        - name: http-trigger
          type: http
          config:
            authType: anonymous
            methods:
              - POST

  worker:
    component: fc
    actions:
      pre-deploy:
        - run: npm install --registry=https://registry.npmmirror.com
          path: "./worker"
        - run: npx prisma generate
          path: "./worker"
      post-deploy:
        - component: fc api UpdateFunction --region ${vars.region} --header '{"x-fc-disable-container-reuse":"True"}' --path '{"serviceName":"${vars.service.name}","functionName":"${vars.workerFunctionName}"}'
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: ${vars.workerFunctionName}
        description: 执行用户配置的 CD 流程。
        runtime: custom
        codeUri: ./worker
        customRuntimeConfig:
          command:
            - node
            - server
        memorySize: 2048
        timeout: 3600
        layers:
          - acs:fc:${vars.region}:official:layers/Nodejs16/versions/1
          - ${vars.sqliteLayer}
        environmentVariables:
          PATH: /opt/nodejs16/bin:/opt:/usr/local/bin/apache-maven/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ruby/bin
          # 用于给用户显示日志链接地址
          DOMAIN: ${vars.domain}
          # 阿里云密钥
          ACCOUNT_ID: ${env.ACCOUNT_ID}
          ACCESS_KEY_ID: ${env.ACCESS_KEY_ID}
          ACCESS_KEY_SECRET: ${env.ACCESS_KEY_SECRET}
          # 上传的OSS地址
          OSS_BUCKET: ${env.OSS_BUCKET}
          # 部署的区域
          REGION: ${vars.region}
          # 用于链接数据库
          DATABASE_URL: ${env.DATABASE_URL}
        asyncConfiguration:
          maxAsyncRetryAttempts: 0
          statefulInvocation: true
          destination:
            onFailure: acs:fc:::services/${vars.service.name}/functions/${vars.workerDeliverFunctionName}

  worker-deliver:
    component: fc
    actions:
      pre-deploy:
        - run: npm install --registry=https://registry.npmmirror.com
          path: "./worker"
        - run: npx prisma generate
          path: "./worker"
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: ${vars.workerDeliverFunctionName}
        description: 执行用户配置的 CD 流程。
        runtime: nodejs14
        codeUri: ./worker
        handler: deliver.handler
        memorySize: 640
        timeout: 600
        layers:
          - ${vars.sqliteLayer}
        environmentVariables:
          PATH: ${vars.path}
          # 部署的区域
          REGION: ${vars.region}
          # 部署函数的服务名称
          SERVICE_NAME: ${vars.service.name}
          # worker 函数的名称
          WORKER_FUNCTION_NAME: ${vars.workerFunctionName}
          # 用于链接数据库
          DATABASE_URL: ${env.DATABASE_URL}
          # 阿里云密钥
          ACCOUNT_ID: ${env.ACCOUNT_ID}
          ACCESS_KEY_ID: ${env.ACCESS_KEY_ID}
          ACCESS_KEY_SECRET: ${env.ACCESS_KEY_SECRET}
        asyncConfiguration:
          maxAsyncRetryAttempts: 0

  admin: # Admin 控制台提供Api Server函数
    component: fc
    actions:
      pre-deploy:
        - run: npm install --registry=https://registry.npmmirror.com --force
          path: "./admin/public"
        - run: npm run build
          path: "./admin/public"
        - run: npm install --registry=https://registry.npmmirror.com
          path: "./admin"
        - run: npx prisma generate
          path: "./admin"
        - plugin: get-http-function-url # 获取依赖的 trigger 函数的触发器地址，会覆盖 environmentVariables 的 WEBHOOK_URL
          args:
            region: ${vars.region}
            serviceName: ${vars.service.name}
            functionName: ${vars.masterFunctionName}
            envKey: WEBHOOK_URL
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: ${vars.adminFunctionName}
        description: serverless-cd 前端应用接口
        runtime: custom
        codeUri: ./admin
        handler: index.handler
        memorySize: 640
        timeout: 360
        caPort: 9000
        instanceConcurrency: 5
        customRuntimeConfig:
          command:
            - node
            - index.js
        layers:
          - acs:fc:cn-hongkong:official:layers/Nodejs16/versions/2
          - ${vars.sqliteLayer}
        environmentVariables:
          PATH: /opt/nodejs16/bin:/opt:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
          # 用于链接数据库
          DATABASE_URL: ${env.DATABASE_URL}
          # 回调地址
          WEBHOOK_URL: ${env.WEBHOOK_URL}
          # 阿里云密钥
          ACCOUNT_ID: ${env.ACCOUNT_ID}
          ACCESS_KEY_ID: ${env.ACCESS_KEY_ID}
          ACCESS_KEY_SECRET: ${env.ACCESS_KEY_SECRET}
          # 部署的区域
          REGION: ${vars.region}
          # 部署函数的服务名称
          SERVICE_NAME: ${vars.service.name}
          # worker 函数的名称
          WORKER_FUNCTION_NAME: ${vars.workerFunctionName}
          # 上传的OSS地址
          OSS_BUCKET: ${env.OSS_BUCKET}
          JWT_SECRET: ${env.JWT_SECRET}
      triggers:
        - name: http-trigger
          type: http
          config:
            authType: anonymous
            methods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
      customDomains:
        - domainName: ${vars.domain}
          protocol: HTTP
          routeConfigs:
            - path: /*
              serviceName: ${vars.service.name}
              functionName: ${vars.adminFunctionName}
