name: Gitee repos mirror periodic job
on:
  # 如果需要PR触发把push前的#去掉
  # push:
  schedule:
    # 每天北京时间9点跑
    - cron:  '0 1 * * *'
      
jobs:
  sync_gitee:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/serverless-cd
        dst: gitee/serverless-cd
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        white_list: "website,serverless-cd,ui,plugins,toolkit"
        account_type: org
